#pragma config(Hubs,  S1, HTServo,  HTMotor,  HTMotor,  none)
#pragma config(Hubs,  S2, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C2_1,     RightDrive,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     LeftDrive,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     Scissor,       tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     CenterDrive,   tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S2_C1_2,     Conveyer,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S2_C1_1,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    TubeGrab,             tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nMotorEncoder[LeftDrive] = 0;
	nMotorEncoder[RightDrive] = 0;
	nMotorEncoder[CenterDrive] = 0;
	nMotorEncoder[Scissor] = 0;
	servo[TubeGrab] = 100;
	wait1Msec(2000);
	servo[TubeGrab] = 150;
	wait1Msec(2000);

	int counter = nPgmTime;

	while((nPgmTime - counter) < 2000){
		motor[Conveyer] = 70;
		wait1Msec(50);
	}

	motor[Conveyer] = 0;

	while((nPgmTime - counter) < 2000){
		motor[LeftDrive] = 20;
		writeDebugStreamLine("%i", nMotorEncoder[LeftDrive]);
		wait1Msec(50);
	}

	counter = nPgmTime;
	while((nPgmTime - counter) < 2000){
		motor[LeftDrive] = -20;
		writeDebugStreamLine("%i", nMotorEncoder[LeftDrive]);
		wait1Msec(50);
	}
	motor[LeftDrive] = 0;

	counter = nPgmTime;
	while((nPgmTime - counter) < 2000){
		motor[RightDrive] = 20;
		writeDebugStreamLine("%i", nMotorEncoder[RightDrive]);
		wait1Msec(50);
	}

	counter = nPgmTime;
	while((nPgmTime - counter) < 2000){
		motor[RightDrive] = -20;
		writeDebugStreamLine("%i", nMotorEncoder[RightDrive]);
		wait1Msec(50);
	}

	motor[RightDrive] = 0;

	counter = nPgmTime;
	while((nPgmTime - counter) < 2000){
		motor[CenterDrive] = 20;
		writeDebugStreamLine("%i", nMotorEncoder[CenterDrive]);
		wait1Msec(50);
	}

	counter = nPgmTime;
	while((nPgmTime - counter) < 2000){
		motor[CenterDrive] = -20;
		writeDebugStreamLine("%i", nMotorEncoder[CenterDrive]);
		wait1Msec(50);
	}

	motor[RightDrive] = 0;

	counter = nPgmTime;
	while((nPgmTime - counter) < 500){
		motor[Scissor] = 10;
		writeDebugStreamLine("%i", nMotorEncoder[Scissor]);
		wait1Msec(50);
	}

	counter = nPgmTime;
	while((nPgmTime - counter) < 500){
		motor[Scissor] = -10;
		writeDebugStreamLine("%i", nMotorEncoder[Scissor]);
		wait1Msec(50);
	}

	motor[RightDrive] = 0;



}
