#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
 * Originally named Nicholai.c, but that was so undescriptive that I just _had_ to change it.
 * Sorry, Matt.
 *
 */

#include "../LibrariesMotors.h"
#include "../Libraries/Servos.h"

#include "JoystickDriver.c"

/*
 * BUTTONS:
 * Button 2 - deploy arm
 * 
 *
 */

void LockArm()
{
	
}

void DeployArm()
{
	
}

task main()
{
	getJoystickSettings(joystick);
	
	while(joy2Btn(2))
	{
		getJoystickSettings(joystick);
		
	}
}
