#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "../Libraries/I2C.h"
#include "../autonomous/IRfunctions - original.c"
#include "../autonomous/IRLineFollower.c"

const int threshold = 18;

void doShit() {
	if(joystick.joy1_y1 > threshold && joystick.joy2_y1 > threshold) {
		I2C_SetMotorSpeed(S1, 1, 1, (joystick.joy1_y1+joystick.joy2_y1)/2);
		I2C_SetMotorSpeed(S1, 1, 2, (joystick.joy1_y1+joystick.joy2_y1)/2);
	}
	else if(joystick.joy1_y2 > threshold && joystick.joy2_y2 > threshold) {
		I2C_SetMotorSpeed(S1, 1, 1, -(joystick.joy1_y2+joystick.joy2_y2)/2);
		I2C_SetMotorSpeed(S1, 1, 2, -(joystick.joy1_y2+joystick.joy2_y2)/2);
	}
	else if(joystick.joy1_x1 > threshold && joystick.joy_x1 > threshold) {
		I2C_SetMotorSpeed(S1, 2, 2, (joystick.joy1_x1+joystick.joy2_x1)/2);
	}
	else if(joystick.joy1_x2 > threshold && joystick.joy2_x2 > threshold) {
		I2C_SetMotorSpeed(S1, 2, 2, -(joystick.joy1_x2+joystick.joy2_x2)/2);
	}
	else if(


}

task main()
{
	while(true) {
		getJoystickSettings(joystick);
		doShit();
	}


}
