#pragma config(Sensor, S1,     ,               sensorI2CCustom)
#pragma config(Sensor, S2,     IRsensor,       sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Libraries/I2C.h"
#include "IRfunctions.c"

const int goal = 20;
int IRvalues[5];
float power[2];

task main() {
	clearDebugStream();
	wait1Msec(1000);
	while(true) {
				calcPower(readIR(S2), goal, power);
				I2C_SetMotorSpeed(S1, 1, 1, (sbyte)-power[0]);
				I2C_SetMotorSpeed(S1, 1, 2, (sbyte)power[0]);
				I2C_SetMotorSpeed(S1, 2, 2, (sbyte)power[1]);
				writeDebugStreamLine("%i", (sbyte)power[0]);
				writeDebugStreamLine("%i", (sbyte)power[1]);

	}

	//	while(true) {
	//	HTIRS2readAllDCStrength(S2, IRvalues[0], IRvalues[1], IRvalues[2], IRvalues[3], IRvalues[4]);
	//	for(int i = 0; i <= 4; i++)
	//	{
	//		writeDebugStreamLine("%i", IRvalues[i]);
	//	}
	//}
}
