#pragma config(Sensor, S1,     ,               sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// IRLineFollower.c

/*

	(C) Copyright 2014 Alex Jordan

	This file is part of the FTC team 6157 application code.

	FTC team 6157 application code is free software: you can
	redistribute it and/or modify it under the terms of the GNU
	General Public License as published by the Free Software
	Foundation, either version 2 of the License, or (at your
	option) any later version.

	FTC team 6157 application code is distributed in the hope that
	it will be useful, but WITHOUT ANY WARRANTY; without even the
	implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
	PURPOSE.  See the GNU General Public License for more details.

	You should have received a copy of the GNU General Public
	License along with FTC team 6157 application code. If not, see
	<http://www.gnu.org/licenses/>.

*/

#include "JoystickDriver.c"

task main()
{

	typedef enum { ONRAMP, MOVEFROMRAMP, LINEFOLLOWING, DISPENSING, KICKSTAND, STOPPED } AutoState;
	AutoState State = STOPPED;

	waitForStart();

	while(true)
	{
		// state machine loop

		switch(State)
		{
			case ONRAMP:
				break;
			case MOVEFROMRAMP:
				break;
			case LINEFOLLOWING:
				break;
			case DISPENSING:
				break;
			case KICKSTAND:
				break;
			case STOPPED:
				// TODO: stop all motors
				Sleep(10);
				break;
			default:
				writeDebugStreamLine("FATAL ERROR ENCOUNTERED");
				writeDebugStreamLine("The state machine has encountered an unknown state. Something is SERIOUSLY wrong!");
				writeDebugStreamLine("Aborting program.");
				// TODO: stop all motors
				StopAllTasks();
				break;
		}
	}

}
