#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorB,          mB,            tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "../Libraries/drivers/lego-ultrasound.h"



task main()
{
	clearDebugStream();
	int sonarRead = 0;
	for(int i = 0; i <= 40; i++)
	{
		motor[mB] = -25;
		motor[mC] = -25;
		wait1Msec(250);
		motor[mB] = 0;
		motor[mC] = 0;
		sonarRead = SensorValue[sonarSensor];
		writeDebugStreamLine("%i", sonarRead);
		wait1Msec(500);
	}
	//while(true) {
	//	//sonarRead = USreadDist(sonarSensor);
	//	sonarRead = SensorValue[sonarSensor];
	//	writeDebugStreamline("%i,", sonarRead);
	//}
}
